add_lunch_combo SoMeX_grouper-userdebug
add_lunch_combo SoMeX_tilapia-userdebug
add_lunch_combo SoMeX_toro-userdebug
add_lunch_combo SoMeX_toroplus-userdebug
add_lunch_combo SoMeX_maguro-userdebug
add_lunch_combo SoMeX_mako-userdebug
add_lunch_combo SoMeX_manta-userdebug
