add_lunch_combo SoMeX_grouper-userdebug
add_lunch_combo SoMeX_hammerhead-userdebug
add_lunch_combo SoMeX_shamu-userdebug
add_lunch_combo SoMeX_grouper-user
add_lunch_combo SoMeX_hammerhead-user
add_lunch_combo SoMeX_shamu-user
